import type { Metadata } from "next";
import { Geist, Geist_Mono, Gabarito } from "next/font/google";
import "./globals.css";
import CartProvider from "./components/cart-provider";
import Header from "./sections/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const gabarito = Gabarito({
  variable: "--font-gabarito",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <CartProvider>
        <body className={`${geistSans.variable} ${geistMono.variable} ${gabarito.variable} antialiased`}>
            <Header/>
            {children}
        </body>
      </CartProvider>
    </html>
  );
}
